# Generated by Django 6.0.7 on 2026-07-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='attends_appointments',
            field=models.BooleanField(default=False),
        ),
    ]
