# Generated by Django 6.0.7 on 2026-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('coordinator', 'Coordinator'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('coordinator', 'Coordinator'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
