# Generated by Django 6.0.7 on 2026-07-27 23:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reminder_lead',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_push_subscription',
                'ordering': ('-created_at',),
            },
        ),
    ]
