# Generated by Django 6.0.7 on 2026-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pushed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
