# Generated by Django 6.0.7 on 2026-08-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_pushed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('appointment_cancelled', 'Appointment cancelled'), ('appointment_requested', 'Appointment requested')], max_length=30),
        ),
    ]
