# Generated by Django 6.0.7 on 2026-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('appointment_cancelled', 'Appointment cancelled'), ('appointment_requested', 'Appointment requested'), ('plan_digest', 'Plan digest')], max_length=30),
        ),
    ]
