# Generated by Django 6.0.7 on 2026-10-07 18:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_plan_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('appointment_cancelled', 'Appointment cancelled'), ('appointment_requested', 'Appointment requested'), ('plan_digest', 'Plan digest'), ('appointment_confirmed', 'Appointment confirmed'), ('appointment_rejected', 'Appointment rejected')], max_length=30),
        ),
    ]
