[project]
name = "amandu-api"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg[binary]>=3.3.4",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=7.0.0",
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
]
