# Generated by Django 6.0.7 on 2026-07-23 00:52

import apps.tenancy.models.tenant
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use an ISO 3166-1 alpha-2 code.')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=63, validators=[apps.tenancy.models.tenant.validate_timezone]),
        ),
    ]
