# Generated by Django 6.0.7 on 2026-08-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenant_country_tenant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
