# Generated by Django 6.0.7 on 2026-08-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_booking',
            field=models.BooleanField(default=False),
        ),
    ]
