# Generated by Django 6.0.7 on 2026-10-02 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenant_public_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plan_digest_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_grace_days',
            field=models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_period_start',
            field=models.CharField(choices=[('month_start', 'Month start'), ('join_day', 'Join day')], default='month_start', max_length=20),
        ),
    ]
