# Generated by Django 6.0.7 on 2026-10-07 18:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenant_plan_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
