# Generated by Django 6.0.7 on 2026-08-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0009_appointmentseries_appointment_series'),
        ('tenancy', '0003_tenant_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.PositiveBigIntegerField()),
                ('occurred_on', models.DateField()),
                ('concept', models.CharField(max_length=140)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='scheduling.appointment')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'cash entries',
                'db_table': 'tb_cash_entry',
                'ordering': ('-occurred_on', '-id'),
                'indexes': [models.Index(fields=['tenant', 'occurred_on'], name='cash_entry_tenant_day_idx')],
            },
        ),
    ]
