# Generated by Django 6.0.7 on 2026-10-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0008_alter_notification_verb'),
        ('scheduling', '0016_plans_and_subscriptions'),
        ('tenancy', '0005_tenant_plan_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='scheduling.client'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='scheduling.subscription'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='void_reason',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='voided_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='voided_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False), ('voided_at__isnull', True)), fields=('subscription', 'period'), name='one_live_payment_per_period'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False), ('client__isnull', False), ('voided_at__isnull', True)), fields=('appointment', 'client'), name='one_live_payment_per_attendee'),
        ),
    ]
