# Generated by Django 6.0.7 on 2026-07-23 20:56

import apps.scheduling.models.appointment
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_attends_appointments'),
        ('scheduling', '0002_category_service_and_more'),
        ('tenancy', '0002_tenant_country_tenant_timezone'),
    ]

    operations = [
        # The exclusion constraint mixes a range operator (GiST) with equality on
        # the professional FK (a scalar). btree_gist adds that operator class;
        # without it the constraint below fails.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.membership')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.service')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tb_appointment',
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_links', to='scheduling.client')),
            ],
            options={
                'db_table': 'tb_appointment_client',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='clients',
            field=models.ManyToManyField(related_name='appointments', through='scheduling.AppointmentClient', to='scheduling.client'),
        ),
        migrations.AddConstraint(
            model_name='appointmentclient',
            constraint=models.UniqueConstraint(fields=('appointment', 'client'), name='unique_client_per_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[(apps.scheduling.models.appointment.TstzRange(models.F('start'), models.F('end')), '&&'), ('professional', '=')], name='no_overlap_per_professional'),
        ),
    ]
