# Generated by Django 6.0.7 on 2026-07-26 15:19

from django.db import migrations, models


def carry_no_show_down_to_the_people(apps, schema_editor):
    """
    `no_show` was the booking's status, which could only ever say "nobody came" --
    useless for a slot holding a group. The fact moves to the person it was always
    about, and the booking keeps the only thing it can honestly claim: it ran.

    Nothing is lost. A pre-existing no_show becomes a completed appointment whose
    every attendee is marked absent, which is what it always meant.
    """
    Appointment = apps.get_model('scheduling', 'Appointment')
    AppointmentClient = apps.get_model('scheduling', 'AppointmentClient')

    absent = Appointment.objects.filter(status='no_show')
    # Evaluated before the update below narrows the set out from under it.
    AppointmentClient.objects.filter(appointment__in=absent).update(attendance='no_show')
    absent.update(status='completed')


def take_it_back_up_to_the_booking(apps, schema_editor):
    """A completed booking nobody attended is what the old status called no_show."""
    Appointment = apps.get_model('scheduling', 'Appointment')

    for appointment in (
        Appointment.objects.filter(status='completed').prefetch_related('client_links')
    ):
        links = list(appointment.client_links.all())
        if links and all(link.attendance == 'no_show' for link in links):
            appointment.status = 'no_show'
            appointment.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_appointmentclient_appointment_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentclient',
            name='attendance',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('no_show', 'No show'), ('late_cancel', 'Late cancellation')], default='pending', max_length=20),
        ),
        # Between the two schema steps on purpose: the column it writes has to
        # exist, and the choice it reads is about to stop being valid.
        migrations.RunPython(carry_no_show_down_to_the_people, take_it_back_up_to_the_booking),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
