# Generated by Django 6.0.7 on 2026-07-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_reminder_lead_pushsubscription'),
        ('scheduling', '0004_appointmentclient_attendance_and_more'),
        ('tenancy', '0002_tenant_country_tenant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start'], name='appointment_start_idx'),
        ),
    ]
