# Generated by Django 6.0.7 on 2026-07-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_appointment_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentclient',
            options={'ordering': ('id',)},
        ),
    ]
