# Generated by Django 6.0.7 on 2026-08-01 20:18

from django.db import migrations, models
from django.db.models import Count


def fit_capacity_to_existing_rosters(apps, schema_editor):
    """
    A slot that already holds more people than the new default must not be born
    invalid. Nothing stopped a group of eight before this field existed, and the
    serializer refuses to save an over-full roster from here on -- so without
    this those appointments would be readable and permanently uneditable, which
    is a worse outcome than the limit not applying to them.

    Raised to exactly what is already booked, never lowered: this migration
    records history, it does not have an opinion about it.
    """
    Appointment = apps.get_model('scheduling', 'Appointment')
    over_full = (
        Appointment.objects
        .annotate(booked=Count('client_links'))
        .filter(booked__gt=models.F('capacity'))
    )
    for appointment in over_full:
        appointment.capacity = appointment.booked
        appointment.save(update_fields=['capacity'])


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_appointmentclient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        # migrations.RunPython.noop in reverse: dropping the column takes these
        # values with it, and there is nothing to restore.
        migrations.RunPython(fit_capacity_to_existing_rosters, migrations.RunPython.noop),
    ]
