# Generated by Django 6.0.7 on 2026-08-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_appointment_capacity'),
        ('tenancy', '0002_tenant_country_tenant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ClientField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/no'), ('select', 'Choice')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tb_client_field',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='unique_client_field_key_per_tenant')],
            },
        ),
    ]
