# Generated by Django 6.0.7 on 2026-08-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_pushed_at'),
        ('scheduling', '0009_appointmentseries_appointment_series'),
        ('tenancy', '0003_tenant_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='accounts.membership')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tb_time_off',
                'ordering': ('start',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='time_off_ends_after_it_starts')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='accounts.membership')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tb_work_schedule',
                'ordering': ('weekday', 'start_time'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='work_schedule_ends_after_it_starts'), models.UniqueConstraint(fields=('professional', 'weekday', 'start_time'), name='unique_work_schedule_start_per_professional_weekday')],
            },
        ),
    ]
