# Generated by Django 6.0.7 on 2026-08-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_appointment_rescheduled_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentclient',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='scheduling.appointmentseries'),
        ),
    ]
