# Generated by Django 6.0.7 on 2026-08-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_appointmentclient_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='monthly_fee',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
