# Generated by Django 6.0.7 on 2026-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_plans_and_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
