# Generated by Django 6.0.7 on 2026-10-07 18:19

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_subscription_anchor_day'),
        ('tenancy', '0006_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('body', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tb_outbound_message',
                'ordering': ('created_at',),
            },
        ),
    ]
